name: problem_details
description: Implementation of ProblemDetails. It is a way to carry machine-readable details of errors in a HTTP response.
version: 0.0.1
homepage: https://github.com/bytes7bytes7/problem_details
repository: https://github.com/bytes7bytes7/problem_details

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
